image: mischief/docker-golang
script:
  - npm test
notify:
  hipchat:
    room: {{hipchatRoom}}
    token: {{hipchatToken}}
    on_started: true
    on_success: true
    on_failure: true
notify:
  email:
    recipients:
      - {{teamEmail1}}
      - {{teamEmail2}}
