image: bradrydzewski/node:0.10
script:
  - npm install
  - npm test
notify:
  hipchat:
    room: {{hipchatRoom}}
    token: {{hipchatToken}}
    on_started: true
    on_success: true
    on_failure: true
  email:
    recipients:
      - {{teamEmail}}
deploy:
  ssh:
    target: ubuntu@{{ip}}:/srv/www/ 22
    artifacts:
      - ./
    cmd: node app.js
